### ISSUE TITLE
infinity loop 

### ISSUE THREAD

**Issue by Ali00** [fnss/fnss#21]
Hi,
Could you please advise me on how to resolve my problem, which is entering to an infinity loop of links whenever I run POX controller to discover the topology.
What I'm doing is generating the network topology within **Brite** tool, then parse the topology within **FNSS**, after that convert it to **Mininet**, I attached my code in below.

Thanks,
[Brite_to_FNSS_to_Mininet.pdf](https://github.com/fnss/fnss/files/736677/Brite_to_FNSS_to_Mininet.pdf)

**Comment by lorenzosaino** [comment]
Hi,

I can't reproduce the issue without your BRITE topology file. Anyway, I looked at the code you sent me and likely your code won't work because Mininet by default does not support topologies with loops, it only supports trees. See my answer to this previous issue: https://github.com/fnss/fnss/issues/12. Does your issue show up even when using tree topologies?

Lorenzo

**Comment by Ali00** [comment]
Hi,

Actually, my Brite topology works fine without "hosts", but the issue of infinity loop occurs when I added the two hosts "h1" and "h2" to the topology. Could you please find my Brite topology file in attached.

Many thanks,
Best regards,
[T1.brite.pdf](https://github.com/fnss/fnss/files/738472/T1.brite.pdf)

**Comment by lorenzosaino** [comment]
Hi Ali, sorry for getting back to you so late on this. Could you please send me the topology file in plaintext format?

**Comment by Ali00** [comment]
Hello LorenzoSaino,

No worries :-) 
Could you please find the attached text topology file. 
Thanks,

[T1.txt](https://github.com/fnss/fnss/files/754693/T1.txt)
