### ISSUE TITLE
Error in example.

### ISSUE THREAD

**Issue by yzexeter** [fnss/fnss#24]
Hi,

I have tried some example codes, causing a keyerror, could you help me with it.
I install the fnss and try the basic code. I modified nothing but get the error below and no other information.
I do not understand what is going on here. I think I can do nothing about it.

python
import fnss
fnss.two_tier_topology(n_core=10, n_edge=20, n_hosts=1)

Traceback (most recent call last):
>>> fnss.two_tier_topology(2,3,4)
Traceback (most recent call last):
  File "\<stdin\>", line 1, in <module>
  File "/home/yz506/anaconda3/envs/nwpy3/lib/python3.6/site-packages/fnss/topologies/datacenter.py", line 91, in two_tier_topology
    topo.node[u]['tier'] = 'core'
  File "/home/yz506/anaconda3/envs/nwpy3/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
    return self._nodes[n]
KeyError: 0

**Comment by lorenzosaino** [comment]
Hi @yzexeter,

This is a known issue and that's because Networkx, a dependency of FNSS, introduced non-backward-compatible changes in version 2.0. The code of FNSS on the master branch pins Networkx to 1.x as a temporary measure (see https://github.com/fnss/fnss/commit/df5dcb2603ac427cc4deaa33f096092504ec20e3) but I haven't made a release of FNSS with that commit yet. I have been working on a branch porting FNSS to Networkx 2.x but it's not finished yet. For the time being, you can fix it by downgrading Networkx to 1.11.

**Comment by lorenzosaino** [comment]
The latest release supports both NetworkX 1.x and 2.x. Closing this issue.
