### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by ana-gonzalezrios** [fnss/fnss#28]
I installed FNSS and tried to run the datacenter examples but I keep receiving "Bus error (core dumped)."
My virtual machine (Multipass) runs Ubuntu 20.04.1 LTS and python 3.8. All required libraries are installed.

**Comment by lorenzosaino** [comment]
Hello,

First of all, please help me validate the issue is specific to FNSS. If you try to run a Python hello world script in your setup, does it work correctly? 

If other Python programs work, could you please confirm this is an issue that happens only when running the datacenter example? If you run the other example, do you have the same problem?

Finally, could you send a full stack trace of the error returned?

**Comment by ana-gonzalezrios** [comment]
Hi Lorenzo,

Correct, if I run a Python hello world script in the setup, it works:
![Screen Shot 2020-09-14 at 11 58 02 AM](https://user-images.githubusercontent.com/59458063/93126713-90df7880-f681-11ea-82d3-12cf4ff64161.png)

Upon further troubleshooting, I noticed that the "Bus error (core dumped)" issue occurs when the following commands are run:

- import fnss

- import networkx

Attached  is a screenshot when trying to run the datacenter.py example.
![image](https://user-images.githubusercontent.com/59458063/93125872-91c3da80-f680-11ea-8ed8-d117b99a766b.png)

Attached are also screenshots showing the error when directly importing the libraries from Python shell.
![Screen Shot 2020-09-14 at 11 55 44 AM](https://user-images.githubusercontent.com/59458063/93126515-4a8a1980-f681-11ea-9ba5-eee51c48cc31.png)
![Screen Shot 2020-09-14 at 11 56 03 AM](https://user-images.githubusercontent.com/59458063/93126518-4bbb4680-f681-11ea-8188-99390b632c1b.png)

**Comment by ana-gonzalezrios** [comment]
I also used gdb:


![Screen Shot 2020-09-14 at 10 51 21 PM](https://user-images.githubusercontent.com/59458063/93170905-eeed7980-f6dc-11ea-8586-59a2f9609f7f.png)

**Comment by lorenzosaino** [comment]
Thanks for the supplementary information. Since the issue is with [networkx](http://github.com/networkx/networkx), which is a third party library, you might need to reach out to their maintainers. I will try to help you anyway to the best of my knowledge.

Looking at potential solutions, I found issues like https://github.com/pytorch/pytorch/issues/2244, which suggest this may be related to insufficient memory available in your virtual machine, which makes sense since bus errors are raised when a process is trying to access memory that cannot be accessed. Could that be your case?

My CI tests run in Ubuntu 20.04 with Python 3.8 and it they are working fine. I do however install some native libraries that are needed by various scientific computing libraries used by FNSS. You could try running these commands (https://github.com/fnss/fnss/blob/master/Makefile#L22-L30) in your VM and see if that fixes it, although I am sure how much it might help.

That's all I can think of. Please let me know if that helps.
Lorenzo

**Comment by ana-gonzalezrios** [comment]
Hi Lorenzo,

Thank you for your support. Turned out that my VM didn't have enough memory. I allowed for more memory and issue got resolved.

**Comment by lorenzosaino** [comment]
Great! Glad to hear that.
